[resolve.alias]
"@/components" = "./app/start/src/web/components"
"@/hooks" = "./app/start/src/web/hooks"
"@/lib" = "./app/start/src/web/lib"
"@/themes" = "./app/start/src/web/themes"
"@/types" = "./app/start/src/web/types"
